describe("template spec", () => {
  it("passes", () => {
    cy.visit("/");
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#a-system-to-organise-projects').should('have.text', 'A system to organise projects');
    cy.get('.large-number > :nth-child(1)').should('have.text', '42.12');
    cy.get('img').should('be.visible');
    cy.get('.output').should('have.text', '11.01 Scope statement $');
    cy.get('.output').should('have.class', 'output');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#areas-and-categories').should('have.text', 'Areas and categories');
    cy.get('.grid.astro-KGOVHDKP > .jd-box').should('have.text', '23.24    31.70\n22.39    13.04\n31.71    21.02\n22.38    13.03\n23.21    23.22\n32.56    12.34\n12.35    21.01\n32.55    23.23');
    cy.get(':nth-child(7) > :nth-child(2)').should('have.text', 'The 31 numbers');
    cy.get('.jd-box.astro-ISULQDGJ > :nth-child(14)').should('have.text', '       23.23  23.24');
    cy.get('img.margin').should('be.visible');
    cy.get('.jd-box.astro-TRGZGO2B > .grid > :nth-child(23)').should('have.text', '    Cleaning contract');
    cy.get('.jd-box.astro-QP6JGH4J > .grid > :nth-child(31) > .area').should('have.text', '30-39 Marketing');
    cy.get('.jd-box.astro-FJ4LFVMJ > .astro-FJ4LFVMJ').should('have.text', 'Administration\nFinance\nMarketing');
    cy.get('pre.astro-MA55RFHV > .highlight').should('have.text', 'Exports         ◀─ new folder');
    cy.get('pre.astro-7MRSQB7Q > .highlight > .bold').should('have.text', ' new folder');
    cy.get('#footnote-1 > p > span').should('have.text', 'I’ve seen countless file systems with numbers in front of folder names, but if they’re not structured it doesn’t work.');
    cy.get('#footnote-2 > p > span > :nth-child(2)').should('have.text', '02');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#ids').should('have.text', 'IDs');
    cy.get(':nth-child(3) > code').should('have.text', '22 Contracts');
    cy.get(':nth-child(8) > code').should('have.text', '22.01 Cleaning contract');
    cy.get('[srcset="/img/11.03-travel-before.gif 2x"]').should('be.visible');
    cy.get('[srcset="/img/11.03-travel-after.gif 2x"]').should('be.visible');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#philosophy').should('have.text', 'Philosophy');
    cy.get('img').should('be.visible');
    cy.get(':nth-child(15) > :nth-child(1) > .area-title').should('have.text', 'Finance and accounts');
    cy.get(':nth-child(6) > .category-number-and-title > .category-title').should('have.text', 'Drawings');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#the-index').should('have.text', 'The index');
    cy.get('.grid > :nth-child(11)').should('have.text', '17.02 Risk mgmt plan');
    cy.get(':nth-child(4) > .id-title').should('have.text', 'My second ID');
    cy.get(':nth-child(16) > :nth-child(4)').should('have.text', 'Document.doc');
    cy.get(':nth-child(16) > :nth-child(6)').should('have.class', 'strikethrough');
    cy.get('[srcset="/img/11.05-bear-filter-17.webp 2x"]').should('be.visible');
    cy.get('[srcset="/img/11.05-bear-new-17.04.wepb 2x"]').should('be.visible');
    cy.get('[srcset="/img/11.05-bear-00.00-the-index.webp 2x"]').should('be.visible');
    cy.get('[srcset="/img/11.05-bear-17.03-location.webp 2x"]').should('be.visible');
    cy.get('#footnote-2 > p > span').should('have.text', 'That link earns me a $10 referral credit if you sign up. If you’d rather not do that, that’s cool: just go to airtable.com. You can copy the template database either way.');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#saving-files').should('have.text', 'Saving files');
    cy.get('img.astro-C5WWVE4S').should('be.visible');
    cy.get('img.astro-C5OVUFM6').should('be.visible');
    cy.get('img.astro-SCACJNUD').should('be.visible');
    cy.get('div.astro-SCACJNUD > :nth-child(3)').should('have.text', '\n      Find what category that something is, and if it doesn\'t exist, create it.\n      Then create a new Johnny.Decimal number inside that category, and store your document there.\n    ');
    cy.get('img.astro-X4GUZIAN').should('be.visible');
    cy.get(':nth-child(1) > .astro-X4GUZIAN').should('have.text', '\n        "Surely you don\'t have to create separate Johnny.Decimal numbers and\n        folders for each of those things?",\n      ');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#keeping-notes').should('have.text', 'Keeping notes');
    cy.get('img').should('be.visible');
    cy.get(':nth-child(26) > strong').should('have.text', 'create a notes system that allows you to store things so that you can find them again.');
    cy.get('.next > .astro-P4YQNH7V').click();
    cy.get('#the-librarian').should('have.text', 'The Librarian');
    cy.get('#isnt-this-the-pmos-job').should('have.text', '“Isn’t this the PMO’s job?”');
    cy.get(':nth-child(20) > .id > :nth-child(6)').click();
    cy.get(':nth-child(22) > .id > :nth-child(4)').click();
    cy.get(':nth-child(23) > .id > :nth-child(4)').click();
    cy.get(':nth-child(24) > .id > :nth-child(4)').click();
    cy.get(':nth-child(25) > .id > :nth-child(4)').click();
    cy.get(':nth-child(26) > .id > :nth-child(4)').click();
    cy.get(':nth-child(27) > .id > :nth-child(4)').click();
    cy.get(':nth-child(28) > .id > :nth-child(4)').click();
    cy.get('.category > :nth-child(5)').click();
    cy.get('code').should('have.text', '11 Core concepts');
    cy.get(':nth-child(18) > .area > :nth-child(3)').click();
    cy.get('code').should('have.text', '10-19 Concepts');
    /* ==== End Cypress Studio ==== */
  });
});
