// I could be generated by Astro.glob, that's basically how you put
// this together (but console.logging it out).
// In which case you'd want a way of excluding pages that you don't
// want in the BackNext structure, i.e. AC.

export const pages = [
  {
    pathname: "/00-09-site-administration/01-about/01.01-colophon/",
    title: "Colophon",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.02-licence/",
    title: "Licence",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.03-privacy/",
    title: "Privacy",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.04-version/",
    title: "Version",
  },
  {
    pathname:
      "/00-09-site-administration/02-send-and-receive/02.01-contact-me/",
    title: "Contact me",
  },
  {
    pathname:
      "/00-09-site-administration/02-send-and-receive/02.02-mailing-list",
    title: "Mailing list",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/02.03-rss-feed/",
    title: "RSS feed",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/02.04-github/",
    title: "GitHub",
  },
  {
    pathname: "/00-09-site-administration/03-settings/03.01-theme/",
    title: "Theme",
  },
  {
    pathname: "/00-09-site-administration/03-settings/03.02-language/",
    title: "Language",
  },
  {
    pathname: "/00-09-site-administration/04-give-me-money/04.01-support-me/",
    title: "Support me",
  },
  {
    pathname: "/00-09-site-administration/04-give-me-money/04.02-consulting/",
    title: "Consulting",
  },
  { pathname: undefined },
  {
    pathname: "/10-19-concepts/11-core/11.01-introduction/",
    title: "Introduction",
  },
  {
    pathname: "/10-19-concepts/11-core/11.02-areas-and-categories/",
    title: "Areas and categories",
  },
  { pathname: "/10-19-concepts/11-core/11.03-ids/", title: "IDs" },
  {
    pathname: "/10-19-concepts/11-core/11.04-philosophy/",
    title: "Philosophy",
  },
  { pathname: "/10-19-concepts/11-core/11.05-the-index/", title: "The index" },
  {
    pathname: "/10-19-concepts/11-core/11.06-saving-files/",
    title: "Saving files",
  },
  {
    pathname: "/10-19-concepts/11-core/11.07-keeping-notes/",
    title: "Keeping notes",
  },
  {
    pathname: "/10-19-concepts/11-core/11.08-the-librarian/",
    title: "The Librarian",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.01-managing-email/",
    title: "Managing email",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.02-exceptions-to-the-rules/",
    title: "Exceptions to the rules",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.03-what-about-00-09/",
    title: "What about 00-09?",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.04-working-at-the-command-line/",
    title: "Working at the command line",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.05-acid-notation/",
    title: "AC.ID notation",
  },
  {
    pathname: "/10-19-concepts/13-multiple-projects/13.01-introduction/",
    title: "Multiple projects",
  },
  {
    pathname: "/10-19-concepts/14-build-your-system/14.01-introduction/",
    title: "Build your system",
  },
  { pathname: undefined },
  {
    pathname: "/20-29-community/21-forums-and-chat/21.01-the-forum/",
    title: "The forum",
  },
  {
    pathname: "/20-29-community/21-forums-and-chat/21.02-discord/",
    title: "Discord",
  },
  { pathname: undefined },
];

/** old pages 2023-04-23 
export const pages = [
  { pathname: "/00-09-site-administration/", title: "Site administration" },
  { pathname: "/00-09-site-administration/01-about/", title: "About" },
  {
    pathname: "/00-09-site-administration/01-about/01.01-colophon/",
    title: "Colophon",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.02-licence/",
    title: "Licence",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.03-privacy/",
    title: "Privacy",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.04-version/",
    title: "Version",
  },
  {
    pathname: "/00-09-site-administration/01-about/01.05-changelog/",
    title: "Changelog",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/",
    title: "Send and receive",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/02.01-contact-me/",
    title: "Contact me",
  },
  {
    pathname:
      "/00-09-site-administration/02-send-and-receive/02.02-mailing-list",
    title: "Mailing list",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/02.03-rss-feed/",
    title: "RSS feed",
  },
  {
    pathname: "/00-09-site-administration/02-send-and-receive/02.04-github/",
    title: "GitHub",
  },
  { pathname: "/00-09-site-administration/03-settings/", title: "Settings" },
  {
    pathname: "/00-09-site-administration/03-settings/03.01-theme/",
    title: "Theme",
  },
  {
    pathname: "/00-09-site-administration/03-settings/03.02-language/",
    title: "Language",
  },
  {
    pathname: "/00-09-site-administration/04-give-me-money/",
    title: "Give me money",
  },
  {
    pathname: "/00-09-site-administration/04-give-me-money/04.01-support-me/",
    title: "Support me",
  },
  {
    pathname: "/00-09-site-administration/04-give-me-money/04.02-consulting/",
    title: "Consulting",
  },
  // { pathname: "/404/", title: "Four-oh-four" },
  // { pathname: "/10-19-concepts/", title: "Concepts" },
  // { pathname: "/10-19-concepts/11-core/", title: "Core concepts" },
  {
    pathname: "/10-19-concepts/11-core/11.01-introduction/",
    title: "Introduction",
  },
  {
    pathname: "/10-19-concepts/11-core/11.02-areas-and-categories/",
    title: "Areas and categories",
  },
  { pathname: "/10-19-concepts/11-core/11.03-ids/", title: "IDs" },
  { pathname: "/10-19-concepts/11-core/11.04-philosophy/", title: "Philosophy" },
  { pathname: "/10-19-concepts/11-core/11.05-the-index/", title: "The index" },
  {
    pathname: "/10-19-concepts/11-core/11.06-saving-files/",
    title: "Saving files",
  },
  {
    pathname: "/10-19-concepts/11-core/11.07-keeping-notes/",
    title: "Keeping notes",
  },
  { pathname: "/10-19-concepts/12-advanced/", title: "Advanced concepts" },
  {
    pathname: "/10-19-concepts/12-advanced/12.01-managing-email/",
    title: "Managing email",
  },
  {
    pathname: "/10-19-concepts/12-advanced/12.02-working-at-the-command-line/",
    title: "Working at the command line",
  },
];
*/
